version: "3"

services:
  docker-api-server:
    container_name: notion
    restart: always
    image: notion-api-server:latest
    environment: 
      - NOTION_TOKEN=${NOTION_TOKEN}
    ports:
      - 5000:5000
