version: "3"

services:
  docker-api-server:
    image: 5pecia1/notion-api-server:latest
    container_name: notion-api-server
    restart: always
    environment: 
      - NOTION_TOKEN=${NOTION_TOKEN}
    ports:
      - 5000:5000
